### ISSUE TITLE
variable type used for subproblems

### ISSUE THREAD

**Issue by rdzman** [ProfBragin/SLBLR#1]
In looking over the Python code, I noticed that in ... https://github.com/ProfBragin/SLBLR/blob/c3bdd0957e620a6800f173c0b494dfe7ed3092ff/SLBLR_Python_Cplex_040223.py#L280
... the subproblems appear to be solved with continuous variables, that is, without the integer constraints. The `SLR_Subproblem.mod` code in `SLBLR_Ex1.zip` on the other hand seems to use integer variables, as I would expect.

Am I missing something, or is this a mistake in the Python example code?

_(On an unrelated note, there appears to be a typo in the first term of the objective in `SLR_Subproblem.mod`. The first term is squared.)_

**Comment by ProfBragin** [comment]
In this case, the integer feasible set's convex hull exactly equals the LP relaxed feasible set. In this simple example, the variable type does not matter since the LP solutions will be at the endpoints of the domain, which are integers, hence, the overall coordination is unaffected.

**Comment by rdzman** [comment]
Of course. I should have thought of that ... and actually, after posting this, I eventually did suspect that was exactly the explanation.

Thanks.
