### ISSUE TITLE
constraints in multiplier divergence detection (MDD) problem

### ISSUE THREAD

**Issue by rdzman** [ProfBragin/SLBLR#2]
It appears to me in this code ...

https://github.com/ProfBragin/SLBLR/blob/c3bdd0957e620a6800f173c0b494dfe7ed3092ff/SLBLR_Python_Cplex_040223.py#L191-L197

... that the last constraint added is for the lambda transition immediately preceding the most recent one. That is, the latest lambda values saved in ...

https://github.com/ProfBragin/SLBLR/blob/c3bdd0957e620a6800f173c0b494dfe7ed3092ff/SLBLR_Python_Cplex_040223.py#L180-L181

... do not appear at all in the constraints that are added.

Not being an experienced Python programmer, I initially assumed that the `range(1, self._M - 1)` in line 191 included `m = self._M - 1`, but I discovered while debugging the code (and then checking the [documentation for `range`](https://docs.python.org/3/library/stdtypes.html#typesseq-range)) that the loop ends with `m = self._M - 2`.

Is this intentional? If so, why is the transition to the most recent lambda values not included in the MDD problem?

**Comment by ProfBragin** [comment]
I believe that M-1 was used because the last two terms contain m+1. If the last term is still missing, it is not intentional.

**Comment by rdzman** [comment]
Ok, thanks, that makes more sense then. Since Python `range(1,N)` goes from `1` to `N-1`, it's definitely missing. Not sure how significant the impact is, but I'll see.

I can submit a pull request with the fix if you like.

**Comment by rdzman** [comment]
Actually, I think it's just changing `range(1, self._M - 1)` to `range(1, self._M)` in 191.

Still runs ok ... with very similar result.
